### ISSUE TITLE
More accurate wording in footer

### ISSUE THREAD

**Issue by pylaligand** [pylaligand/gdestiny-site#116]
<img width="387" alt="screen shot 2016-09-01 at 12 19 57 pm" src="https://cloud.githubusercontent.com/assets/1115379/18181101/7bd4a1f4-703e-11e6-8911-566171baf3a8.png">

Not all data and media are property of Bungie. Not sure how to formulate that properly. Or maybe it is actually accurate enough?

**Comment by john-mikhail** [comment]
Yeah wasn't sure how to word it.  Not sure if I should add "Some data/media used..."
