### ISSUE TITLE
KD data set is empty

### ISSUE THREAD

**Issue by john-mikhail** [pylaligand/gdestiny-site#120]
https://gdestiny-server.herokuapp.com/kd returning empty data set

**Comment by john-mikhail** [comment]
Same issue with wins

**Comment by pylaligand** [comment]
This is based on guardian.gg and they've recently changed something in their API. No resolution for now...

**Comment by pylaligand** [comment]
It turns out they had changed some config on the backend and accidentally disabled https. They just fixed it, so I refreshed our database and the request now succeeds.
