### ISSUE TITLE
Update max grimoire in API

### ISSUE THREAD

**Issue by john-mikhail** [pylaligand/gdestiny-site#122]

**Comment by pylaligand** [comment]
Right now I think they are 5100 (XB) and 5140 (PS)

**Comment by john-mikhail** [comment]
Has the API been updated to return the max?  That's not hard coded in the FE, and it's pulled from the API.

**Comment by pylaligand** [comment]
Nope, this was more of a "note to self" kind of message :)

**Comment by pylaligand** [comment]
Nope, this was more of a "note to self" kind of message :)
